// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.3
// Project name: indicator_basis

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_ScreenTime
void ui_ScreenTime_screen_init(void);
lv_obj_t *ui_ScreenTime;
lv_obj_t *ui_ImgBackground;
lv_obj_t *ui_PnlHour;
lv_obj_t *ui_LblHour;
lv_obj_t *ui_PnlMin;
lv_obj_t *ui_LblMin;
lv_obj_t *ui_Pnllocation;
lv_obj_t *ui_LblCity;
lv_obj_t *ui_ImgLocation;
lv_obj_t *ui_PnlDate;
lv_obj_t *ui_LblDate;
lv_obj_t *ui_LblDotTime;
lv_obj_t *ui_PnlSlide;
lv_obj_t *ui_BtnWifi1;
lv_obj_t *ui_LblWifiStatus1;


// SCREEN: ui_ScreenSensor
void ui_ScreenSensor_screen_init(void);
lv_obj_t *ui_ScreenSensor;
lv_obj_t *ui_LblTime1;
lv_obj_t *ui_PnlDots1;
lv_obj_t *ui_PnlDot1;
lv_obj_t *ui_PnlDot2;
lv_obj_t *ui_PnlDot3;
lv_obj_t *ui_BtnHumi1;
lv_obj_t *ui_ImgHumi1;
lv_obj_t *ui_LblTitleHumi1;
lv_obj_t *ui_LblDataHumi1;
lv_obj_t *ui_LblUnitHumi1;
lv_obj_t *ui_BtnCOt1;
lv_obj_t *ui_ImgCOt1;
lv_obj_t *ui_LblTitleCOt1;
lv_obj_t *ui_LblDataCOt1;
lv_obj_t *ui_LblUnitCOt1;
lv_obj_t *ui_BtnTVOC1;
lv_obj_t *ui_ImgTVOC1;
lv_obj_t *ui_LblTitleTVOC1;
lv_obj_t *ui_LblDataTVOC1;
lv_obj_t *ui_LblUnitTVOC1;
lv_obj_t *ui_BtnTmp1;
lv_obj_t *ui_ImgTmp1;
lv_obj_t *ui_LblTitleTmp1;
lv_obj_t *ui_LblDataTmp1;
lv_obj_t *ui_LblUnitTmp1;
lv_obj_t *ui_BtnWifi2;
lv_obj_t *ui_LblWifiStatus2;


// SCREEN: ui_ScreenSetting
void ui_ScreenSetting_screen_init(void);
lv_obj_t *ui_ScreenSetting;
lv_obj_t *ui_LblTime2;
lv_obj_t *ui_ImgSetting1;
lv_obj_t *ui_LblTitleSetting;
lv_obj_t *ui_BtnUsrWifi1;
lv_obj_t *ui_ImgWifi1;
lv_obj_t *ui_LblTitleWIFI1;
lv_obj_t *ui_BtnDateTime1;
lv_obj_t *ui_ImgDateTime1;
lv_obj_t *ui_LblTitleDateTime1;
lv_obj_t *ui_BtnDisplay1;
lv_obj_t *ui_ImgDisplay1;
lv_obj_t *ui_LblTitleDisplay1;
lv_obj_t *ui_BtnWifi3;
lv_obj_t *ui_LblWifiStatus3;
lv_obj_t *ui_PnlDots2;
lv_obj_t *ui_PnlDot4;
lv_obj_t *ui_PnlDot5;
lv_obj_t *ui_PnlDot6;


// SCREEN: ui_ScreenWIFI
void ui_ScreenWIFI_screen_init(void);
lv_obj_t *ui_ScreenWIFI;
lv_obj_t *ui_BtnBackSWifi;
lv_obj_t *ui_LblTitleWifi;
lv_obj_t *ui_BtnWifi4;
lv_obj_t *ui_LblWifiStatus4;


// SCREEN: ui_ScreenDisplay
void ui_ScreenDisplay_screen_init(void);
lv_obj_t *ui_ScreenDisplay;
lv_obj_t *ui_sleep_mode_time1;
lv_obj_t *ui_after1;
lv_obj_t *ui_sleep_mode_time_cfg1;
lv_obj_t *ui_min2;
lv_obj_t *ui_sleep_mode1;
lv_obj_t *ui_sleep_mode_title1;
lv_obj_t *ui_sleep_mode_cfg1;
lv_obj_t *ui_brighness1;
lv_obj_t *ui_brighness_cfg1;
lv_obj_t *ui_brighness_title1;
lv_obj_t *ui_brighness_icon_3;
lv_obj_t *ui_brighness_icon_4;
lv_obj_t *ui_display_keyboard1;
lv_obj_t *ui_LblTitleDisplay;
lv_obj_t *ui_BtnBackSDisplay;
lv_obj_t *ui_BtnWifi5;
lv_obj_t *ui_LblWifiStatus5;


// SCREEN: ui_ScreenDatetime
void ui_ScreenDatetime_screen_init(void);
lv_obj_t *ui_ScreenDatetime;
lv_obj_t *ui_date_time1;
lv_obj_t *ui_time_zone_title1;
lv_obj_t *ui_time_zone_num_cfg1;
lv_obj_t *ui_utc_tile1;
lv_obj_t *ui_time_zone_sign_cfg_1;
lv_obj_t *ui_daylight_title1;
lv_obj_t *ui_daylight_cfg1;
lv_obj_t *ui_manual_setting_title1;
lv_obj_t *ui_date_cfg1;
lv_obj_t *ui_hour_cfg2;
lv_obj_t *ui_min_cfg2;
lv_obj_t *ui_sec_cfg1;
lv_obj_t *ui_time_label3;
lv_obj_t *ui_time_label4;
lv_obj_t *ui_auto_update1;
lv_obj_t *ui_auto_update_title1;
lv_obj_t *ui_auto_update_cfg1;
lv_obj_t *ui_time_format1;
lv_obj_t *ui_time_format_title1;
lv_obj_t *ui_time_format_cfg1;
lv_obj_t *ui_BtnBackSDateTime;
lv_obj_t *ui_LblTitleDateTime;
lv_obj_t *ui_BtnWifi6;
lv_obj_t *ui_LblWifiStatus6;


// SCREEN: ui_ScreenHistory
void ui_ScreenHistory_screen_init(void);
lv_obj_t *ui_ScreenHistory;
lv_obj_t *ui_BtnBackSHistory;
lv_obj_t *ui_LblTitleWifi1;
lv_obj_t *ui_BtnWifi7;
lv_obj_t *ui_LblWifiStatus7;
lv_obj_t *ui_PnlHistory;
lv_obj_t *ui_TabView2;
lv_obj_t *ui_TabPageDay;
lv_obj_t *ui_ChartDay;
lv_obj_t *ui_TabPageWeek;
lv_obj_t *ui_ChartWeek;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_co[1] = {&ui_img_co2_png};
const lv_img_dsc_t *ui_imgset_humidity_[2] = {&ui_img_humidity_1_png, &ui_img_humidity_2_png};
const lv_img_dsc_t *ui_imgset_location[1] = {&ui_img_location2_png};
const lv_img_dsc_t *ui_imgset_temp_[2] = {&ui_img_temp_1_png, &ui_img_temp_2_png};
const lv_img_dsc_t *ui_imgset_wifi_[3] = {&ui_img_wifi_1_png, &ui_img_wifi_2_png, &ui_img_wifi_3_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_ScreenTime_screen_init();
ui_ScreenSensor_screen_init();
ui_ScreenSetting_screen_init();
ui_ScreenWIFI_screen_init();
ui_ScreenDisplay_screen_init();
ui_ScreenDatetime_screen_init();
ui_ScreenHistory_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_ScreenTime);
}
