// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.3
// Project name: indicator_basis

#ifndef _INDICATOR_BASIS_UI_H
#define _INDICATOR_BASIS_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_ScreenTime
void ui_ScreenTime_screen_init(void);
extern lv_obj_t *ui_ScreenTime;
extern lv_obj_t *ui_ImgBackground;
extern lv_obj_t *ui_PnlHour;
extern lv_obj_t *ui_LblHour;
extern lv_obj_t *ui_PnlMin;
extern lv_obj_t *ui_LblMin;
extern lv_obj_t *ui_Pnllocation;
extern lv_obj_t *ui_LblCity;
extern lv_obj_t *ui_ImgLocation;
extern lv_obj_t *ui_PnlDate;
extern lv_obj_t *ui_LblDate;
extern lv_obj_t *ui_LblDotTime;
extern lv_obj_t *ui_PnlSlide;
extern lv_obj_t *ui_BtnWifi1;
extern lv_obj_t *ui_LblWifiStatus1;
// SCREEN: ui_ScreenSensor
void ui_ScreenSensor_screen_init(void);
extern lv_obj_t *ui_ScreenSensor;
extern lv_obj_t *ui_LblTime1;
extern lv_obj_t *ui_PnlDots1;
extern lv_obj_t *ui_PnlDot1;
extern lv_obj_t *ui_PnlDot2;
extern lv_obj_t *ui_PnlDot3;
extern lv_obj_t *ui_BtnHumi1;
extern lv_obj_t *ui_ImgHumi1;
extern lv_obj_t *ui_LblTitleHumi1;
extern lv_obj_t *ui_LblDataHumi1;
extern lv_obj_t *ui_LblUnitHumi1;
extern lv_obj_t *ui_BtnCOt1;
extern lv_obj_t *ui_ImgCOt1;
extern lv_obj_t *ui_LblTitleCOt1;
extern lv_obj_t *ui_LblDataCOt1;
extern lv_obj_t *ui_LblUnitCOt1;
extern lv_obj_t *ui_BtnTVOC1;
extern lv_obj_t *ui_ImgTVOC1;
extern lv_obj_t *ui_LblTitleTVOC1;
extern lv_obj_t *ui_LblDataTVOC1;
extern lv_obj_t *ui_LblUnitTVOC1;
extern lv_obj_t *ui_BtnTmp1;
extern lv_obj_t *ui_ImgTmp1;
extern lv_obj_t *ui_LblTitleTmp1;
extern lv_obj_t *ui_LblDataTmp1;
extern lv_obj_t *ui_LblUnitTmp1;
extern lv_obj_t *ui_BtnWifi2;
extern lv_obj_t *ui_LblWifiStatus2;
// SCREEN: ui_ScreenSetting
void ui_ScreenSetting_screen_init(void);
extern lv_obj_t *ui_ScreenSetting;
extern lv_obj_t *ui_LblTime2;
extern lv_obj_t *ui_ImgSetting1;
extern lv_obj_t *ui_LblTitleSetting;
extern lv_obj_t *ui_BtnUsrWifi1;
extern lv_obj_t *ui_ImgWifi1;
extern lv_obj_t *ui_LblTitleWIFI1;
extern lv_obj_t *ui_BtnDateTime1;
extern lv_obj_t *ui_ImgDateTime1;
extern lv_obj_t *ui_LblTitleDateTime1;
extern lv_obj_t *ui_BtnDisplay1;
extern lv_obj_t *ui_ImgDisplay1;
extern lv_obj_t *ui_LblTitleDisplay1;
extern lv_obj_t *ui_BtnWifi3;
extern lv_obj_t *ui_LblWifiStatus3;
extern lv_obj_t *ui_PnlDots2;
extern lv_obj_t *ui_PnlDot4;
extern lv_obj_t *ui_PnlDot5;
extern lv_obj_t *ui_PnlDot6;
// SCREEN: ui_ScreenWIFI
void ui_ScreenWIFI_screen_init(void);
extern lv_obj_t *ui_ScreenWIFI;
extern lv_obj_t *ui_BtnBackSWifi;
extern lv_obj_t *ui_LblTitleWifi;
extern lv_obj_t *ui_BtnWifi4;
extern lv_obj_t *ui_LblWifiStatus4;
// SCREEN: ui_ScreenDisplay
void ui_ScreenDisplay_screen_init(void);
extern lv_obj_t *ui_ScreenDisplay;
extern lv_obj_t *ui_sleep_mode_time1;
extern lv_obj_t *ui_after1;
extern lv_obj_t *ui_sleep_mode_time_cfg1;
extern lv_obj_t *ui_min2;
extern lv_obj_t *ui_sleep_mode1;
extern lv_obj_t *ui_sleep_mode_title1;
extern lv_obj_t *ui_sleep_mode_cfg1;
extern lv_obj_t *ui_brighness1;
extern lv_obj_t *ui_brighness_cfg1;
extern lv_obj_t *ui_brighness_title1;
extern lv_obj_t *ui_brighness_icon_3;
extern lv_obj_t *ui_brighness_icon_4;
extern lv_obj_t *ui_display_keyboard1;
extern lv_obj_t *ui_LblTitleDisplay;
extern lv_obj_t *ui_BtnBackSDisplay;
extern lv_obj_t *ui_BtnWifi5;
extern lv_obj_t *ui_LblWifiStatus5;
// SCREEN: ui_ScreenDatetime
void ui_ScreenDatetime_screen_init(void);
extern lv_obj_t *ui_ScreenDatetime;
extern lv_obj_t *ui_date_time1;
extern lv_obj_t *ui_time_zone_title1;
extern lv_obj_t *ui_time_zone_num_cfg1;
extern lv_obj_t *ui_utc_tile1;
extern lv_obj_t *ui_time_zone_sign_cfg_1;
extern lv_obj_t *ui_daylight_title1;
extern lv_obj_t *ui_daylight_cfg1;
extern lv_obj_t *ui_manual_setting_title1;
extern lv_obj_t *ui_date_cfg1;
extern lv_obj_t *ui_hour_cfg2;
extern lv_obj_t *ui_min_cfg2;
extern lv_obj_t *ui_sec_cfg1;
extern lv_obj_t *ui_time_label3;
extern lv_obj_t *ui_time_label4;
extern lv_obj_t *ui_auto_update1;
extern lv_obj_t *ui_auto_update_title1;
extern lv_obj_t *ui_auto_update_cfg1;
extern lv_obj_t *ui_time_format1;
extern lv_obj_t *ui_time_format_title1;
extern lv_obj_t *ui_time_format_cfg1;
extern lv_obj_t *ui_BtnBackSDateTime;
extern lv_obj_t *ui_LblTitleDateTime;
extern lv_obj_t *ui_BtnWifi6;
extern lv_obj_t *ui_LblWifiStatus6;
// SCREEN: ui_ScreenHistory
void ui_ScreenHistory_screen_init(void);
extern lv_obj_t *ui_ScreenHistory;
extern lv_obj_t *ui_BtnBackSHistory;
extern lv_obj_t *ui_LblTitleWifi1;
extern lv_obj_t *ui_BtnWifi7;
extern lv_obj_t *ui_LblWifiStatus7;
extern lv_obj_t *ui_PnlHistory;
extern lv_obj_t *ui_TabView2;
extern lv_obj_t *ui_TabPageDay;
extern lv_obj_t *ui_ChartDay;
extern lv_obj_t *ui_TabPageWeek;
extern lv_obj_t *ui_ChartWeek;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_background_png);   // assets\background.png
LV_IMG_DECLARE( ui_img_location2_png);   // assets\location2.png
LV_IMG_DECLARE( ui_img_wifi_disconet_png);   // assets\wifi_disconet.png
LV_IMG_DECLARE( ui_img_humidity_2_png);   // assets\humidity_2.png
LV_IMG_DECLARE( ui_img_co2_png);   // assets\co2.png
LV_IMG_DECLARE( ui_img_tvoc_png);   // assets\tvoc.png
LV_IMG_DECLARE( ui_img_temp_2_png);   // assets\temp_2.png
LV_IMG_DECLARE( ui_img_setting_png);   // assets\setting.png
LV_IMG_DECLARE( ui_img_wifi_setting_png);   // assets\wifi_setting.png
LV_IMG_DECLARE( ui_img_time_png);   // assets\time.png
LV_IMG_DECLARE( ui_img_display_png);   // assets\display.png
LV_IMG_DECLARE( ui_img_back_png);   // assets\back.png
LV_IMG_DECLARE( ui_img_high_light_png);   // assets\high_light.png
LV_IMG_DECLARE( ui_img_low_light_png);   // assets\low_light.png
LV_IMG_DECLARE( ui_img_humidity_1_png);   // assets\humidity_1.png
LV_IMG_DECLARE( ui_img_temp_1_png);   // assets\temp_1.png
LV_IMG_DECLARE( ui_img_wifi_1_png);   // assets\wifi_1.png
LV_IMG_DECLARE( ui_img_wifi_2_png);   // assets\wifi_2.png
LV_IMG_DECLARE( ui_img_wifi_3_png);   // assets\wifi_3.png

LV_FONT_DECLARE( ui_font_font0);
LV_FONT_DECLARE( ui_font_font1);
LV_FONT_DECLARE( ui_font_font2);
LV_FONT_DECLARE( ui_font_font3);
LV_FONT_DECLARE( ui_font_font4);
LV_FONT_DECLARE( ui_font_Font1);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
