// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.3
// Project name: indicator_basis

#include "../ui.h"

void ui_ScreenTime_screen_init(void)
{
ui_ScreenTime = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenTime, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ImgBackground = lv_img_create(ui_ScreenTime);
lv_img_set_src(ui_ImgBackground, &ui_img_background_png);
lv_obj_set_width( ui_ImgBackground, lv_pct(100));
lv_obj_set_height( ui_ImgBackground, lv_pct(100));
lv_obj_set_align( ui_ImgBackground, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImgBackground, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImgBackground, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_PnlHour = lv_obj_create(ui_ImgBackground);
lv_obj_set_width( ui_PnlHour, 200);
lv_obj_set_height( ui_PnlHour, 170);
lv_obj_set_x( ui_PnlHour, -110 );
lv_obj_set_y( ui_PnlHour, 0 );
lv_obj_set_align( ui_PnlHour, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PnlHour, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_PnlHour, lv_color_hex(0x2E2E2E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PnlHour, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LblHour = lv_label_create(ui_PnlHour);
lv_obj_set_width( ui_LblHour, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LblHour, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LblHour, LV_ALIGN_CENTER );
lv_label_set_text(ui_LblHour,"20");
lv_obj_set_style_text_font(ui_LblHour, &ui_font_Font1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PnlMin = lv_obj_create(ui_ImgBackground);
lv_obj_set_width( ui_PnlMin, 200);
lv_obj_set_height( ui_PnlMin, 170);
lv_obj_set_x( ui_PnlMin, 110 );
lv_obj_set_y( ui_PnlMin, 0 );
lv_obj_set_align( ui_PnlMin, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PnlMin, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_PnlMin, lv_color_hex(0x2E2E2E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PnlMin, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LblMin = lv_label_create(ui_PnlMin);
lv_obj_set_width( ui_LblMin, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LblMin, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LblMin, LV_ALIGN_CENTER );
lv_label_set_text(ui_LblMin,"23");
lv_obj_set_style_text_font(ui_LblMin, &ui_font_Font1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Pnllocation = lv_obj_create(ui_ImgBackground);
lv_obj_set_width( ui_Pnllocation, 399);
lv_obj_set_height( ui_Pnllocation, 30);
lv_obj_set_x( ui_Pnllocation, 6 );
lv_obj_set_y( ui_Pnllocation, 103 );
lv_obj_set_align( ui_Pnllocation, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Pnllocation, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Pnllocation, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Pnllocation, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Pnllocation, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_color(ui_Pnllocation, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Pnllocation, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LblCity = lv_label_create(ui_Pnllocation);
lv_obj_set_width( ui_LblCity, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LblCity, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LblCity, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_LblCity,"Shen Zhen");
lv_obj_set_style_text_font(ui_LblCity, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImgLocation = lv_img_create(ui_ImgBackground);
lv_img_set_src(ui_ImgLocation, &ui_img_location2_png);
lv_obj_set_width( ui_ImgLocation, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImgLocation, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImgLocation, 199 );
lv_obj_set_y( ui_ImgLocation, 103 );
lv_obj_set_align( ui_ImgLocation, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImgLocation, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImgLocation, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_PnlDate = lv_obj_create(ui_ImgBackground);
lv_obj_set_width( ui_PnlDate, 235);
lv_obj_set_height( ui_PnlDate, 30);
lv_obj_set_x( ui_PnlDate, -103 );
lv_obj_set_y( ui_PnlDate, -108 );
lv_obj_set_align( ui_PnlDate, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PnlDate, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_PnlDate, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PnlDate, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_PnlDate, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_color(ui_PnlDate, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PnlDate, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LblDate = lv_label_create(ui_PnlDate);
lv_obj_set_width( ui_LblDate, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LblDate, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LblDate, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_LblDate,"Monday, 06 / 03 /  2023");
lv_label_set_recolor(ui_LblDate,"true");
lv_obj_set_style_text_font(ui_LblDate, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LblDotTime = lv_label_create(ui_ImgBackground);
lv_obj_set_width( ui_LblDotTime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LblDotTime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LblDotTime, LV_ALIGN_CENTER );
lv_label_set_text(ui_LblDotTime,":");
lv_obj_set_style_text_font(ui_LblDotTime, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PnlSlide = lv_obj_create(ui_ImgBackground);
lv_obj_set_width( ui_PnlSlide, 480);
lv_obj_set_height( ui_PnlSlide, 6);
lv_obj_set_align( ui_PnlSlide, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PnlSlide, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_PnlSlide, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PnlSlide, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_PnlSlide, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_color(ui_PnlSlide, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PnlSlide, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BtnWifi1 = lv_btn_create(ui_ScreenTime);
lv_obj_set_width( ui_BtnWifi1, 60);
lv_obj_set_height( ui_BtnWifi1, 60);
lv_obj_set_x( ui_BtnWifi1, -10 );
lv_obj_set_y( ui_BtnWifi1, 10 );
lv_obj_set_align( ui_BtnWifi1, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_BtnWifi1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BtnWifi1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_BtnWifi1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BtnWifi1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LblWifiStatus1 = lv_img_create(ui_BtnWifi1);
lv_img_set_src(ui_LblWifiStatus1, &ui_img_wifi_disconet_png);
lv_obj_set_width( ui_LblWifiStatus1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LblWifiStatus1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LblWifiStatus1, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_LblWifiStatus1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_LblWifiStatus1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

}
