// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.3
// Project name: indicator_basis

#include "../ui.h"

void ui_ScreenHistory_screen_init(void)
{
ui_ScreenHistory = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenHistory, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BtnBackSHistory = lv_btn_create(ui_ScreenHistory);
lv_obj_set_width( ui_BtnBackSHistory, 100);
lv_obj_set_height( ui_BtnBackSHistory, 50);
lv_obj_set_x( ui_BtnBackSHistory, 10 );
lv_obj_set_y( ui_BtnBackSHistory, 30 );
lv_obj_add_flag( ui_BtnBackSHistory, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BtnBackSHistory, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_BtnBackSHistory, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BtnBackSHistory, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_BtnBackSHistory, &ui_img_back_png, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_LblTitleWifi1 = lv_label_create(ui_ScreenHistory);
lv_obj_set_width( ui_LblTitleWifi1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LblTitleWifi1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LblTitleWifi1, 1 );
lv_obj_set_y( ui_LblTitleWifi1, 50 );
lv_obj_set_align( ui_LblTitleWifi1, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_LblTitleWifi1,"Title");
lv_obj_set_style_text_font(ui_LblTitleWifi1, &ui_font_font1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BtnWifi7 = lv_btn_create(ui_ScreenHistory);
lv_obj_set_width( ui_BtnWifi7, 60);
lv_obj_set_height( ui_BtnWifi7, 60);
lv_obj_set_x( ui_BtnWifi7, -10 );
lv_obj_set_y( ui_BtnWifi7, 10 );
lv_obj_set_align( ui_BtnWifi7, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_BtnWifi7, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BtnWifi7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_BtnWifi7, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BtnWifi7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_BtnWifi7, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT );

ui_LblWifiStatus7 = lv_img_create(ui_BtnWifi7);
lv_img_set_src(ui_LblWifiStatus7, &ui_img_wifi_disconet_png);
lv_obj_set_width( ui_LblWifiStatus7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LblWifiStatus7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LblWifiStatus7, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_LblWifiStatus7, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_LblWifiStatus7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_PnlHistory = lv_obj_create(ui_ScreenHistory);
lv_obj_set_width( ui_PnlHistory, 480);
lv_obj_set_height( ui_PnlHistory, 400);
lv_obj_set_align( ui_PnlHistory, LV_ALIGN_BOTTOM_MID );
lv_obj_clear_flag( ui_PnlHistory, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_PnlHistory, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PnlHistory, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PnlHistory, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PnlHistory, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TabView2 = lv_tabview_create(ui_PnlHistory, LV_DIR_TOP, 50);
lv_obj_set_width( ui_TabView2, 460);
lv_obj_set_height( ui_TabView2, 380);
lv_obj_set_align( ui_TabView2, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_TabView2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_TabView2), lv_color_hex(0x65C367),  LV_PART_ITEMS | LV_STATE_CHECKED );
lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_TabView2), 255,  LV_PART_ITEMS| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_TabView2), lv_color_hex(0x65C367),  LV_PART_ITEMS | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_TabView2), 50,  LV_PART_ITEMS| LV_STATE_CHECKED);
lv_obj_set_style_border_color(lv_tabview_get_tab_btns(ui_TabView2), lv_color_hex(0x65C367),  LV_PART_ITEMS | LV_STATE_CHECKED );
lv_obj_set_style_border_opa(lv_tabview_get_tab_btns(ui_TabView2), 255,  LV_PART_ITEMS| LV_STATE_CHECKED);

ui_TabPageDay = lv_tabview_add_tab(ui_TabView2, "Day");

ui_ChartDay = lv_chart_create(ui_TabPageDay);
lv_obj_set_width( ui_ChartDay, 400);
lv_obj_set_height( ui_ChartDay, 260);
lv_obj_set_align( ui_ChartDay, LV_ALIGN_CENTER );
lv_chart_set_type( ui_ChartDay, LV_CHART_TYPE_LINE);
lv_chart_set_point_count( ui_ChartDay, 7);
lv_chart_set_div_line_count( ui_ChartDay, 0, 7);
lv_chart_set_zoom_x( ui_ChartDay, 255);
lv_chart_set_zoom_y( ui_ChartDay, 255);
lv_chart_set_axis_tick( ui_ChartDay, LV_CHART_AXIS_PRIMARY_X, 0, 0, 7, 1, true, 50);
lv_chart_set_axis_tick( ui_ChartDay, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, false, 50);
lv_chart_set_axis_tick( ui_ChartDay, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, false, 25);
lv_chart_series_t* ui_ChartDay_series_1 = lv_chart_add_series(ui_ChartDay, lv_color_hex(0x65C367), LV_CHART_AXIS_PRIMARY_Y);
static lv_coord_t ui_ChartDay_series_1_array[] = { 0,80,80,40,10,20,40 };
lv_chart_set_ext_y_array(ui_ChartDay, ui_ChartDay_series_1, ui_ChartDay_series_1_array);
lv_obj_set_style_bg_color(ui_ChartDay, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ChartDay, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_ChartDay, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ChartDay, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_ChartDay, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_ChartDay, 0, LV_PART_MAIN| LV_STATE_DEFAULT);


lv_obj_set_style_border_color(ui_ChartDay, lv_color_hex(0x9F2121), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ChartDay, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_line_color(ui_ChartDay, lv_color_hex(0x4040FF), LV_PART_TICKS | LV_STATE_DEFAULT );
lv_obj_set_style_line_opa(ui_ChartDay, 0, LV_PART_TICKS| LV_STATE_DEFAULT);

ui_TabPageWeek = lv_tabview_add_tab(ui_TabView2, "Week");

ui_ChartWeek = lv_chart_create(ui_TabPageWeek);
lv_obj_set_width( ui_ChartWeek, 400);
lv_obj_set_height( ui_ChartWeek, 260);
lv_obj_set_align( ui_ChartWeek, LV_ALIGN_CENTER );
lv_chart_set_type( ui_ChartWeek, LV_CHART_TYPE_LINE);
lv_chart_set_point_count( ui_ChartWeek, 7);
lv_chart_set_div_line_count( ui_ChartWeek, 0, 7);
lv_chart_set_zoom_x( ui_ChartWeek, 255);
lv_chart_set_zoom_y( ui_ChartWeek, 255);
lv_chart_set_axis_tick( ui_ChartWeek, LV_CHART_AXIS_PRIMARY_X, 0, 0, 7, 1, true, 50);
lv_chart_set_axis_tick( ui_ChartWeek, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, false, 50);
lv_chart_set_axis_tick( ui_ChartWeek, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, false, 25);
lv_chart_series_t* ui_ChartWeek_series_1 = lv_chart_add_series(ui_ChartWeek, lv_color_hex(0x65C367), LV_CHART_AXIS_PRIMARY_Y);
static lv_coord_t ui_ChartWeek_series_1_array[] = { 0,80,80,40,10,20,40 };
lv_chart_set_ext_y_array(ui_ChartWeek, ui_ChartWeek_series_1, ui_ChartWeek_series_1_array);
lv_obj_set_style_bg_color(ui_ChartWeek, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ChartWeek, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_ChartWeek, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ChartWeek, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_ChartWeek, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_ChartWeek, 0, LV_PART_MAIN| LV_STATE_DEFAULT);


lv_obj_set_style_border_color(ui_ChartWeek, lv_color_hex(0x9F2121), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ChartWeek, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_line_color(ui_ChartWeek, lv_color_hex(0x4040FF), LV_PART_TICKS | LV_STATE_DEFAULT );
lv_obj_set_style_line_opa(ui_ChartWeek, 0, LV_PART_TICKS| LV_STATE_DEFAULT);

}
