// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.3
// Project name: indicator_basis

#include "../ui.h"

void ui_ScreenSensor_screen_init(void)
{
ui_ScreenSensor = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenSensor, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LblTime1 = lv_label_create(ui_ScreenSensor);
lv_obj_set_width( ui_LblTime1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LblTime1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LblTime1, 30 );
lv_obj_set_y( ui_LblTime1, 20 );
lv_label_set_text(ui_LblTime1,"21:20");
lv_obj_set_style_text_font(ui_LblTime1, &ui_font_font1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PnlDots1 = lv_obj_create(ui_ScreenSensor);
lv_obj_set_width( ui_PnlDots1, 100);
lv_obj_set_height( ui_PnlDots1, 20);
lv_obj_set_x( ui_PnlDots1, 0 );
lv_obj_set_y( ui_PnlDots1, -20 );
lv_obj_set_align( ui_PnlDots1, LV_ALIGN_BOTTOM_MID );
lv_obj_clear_flag( ui_PnlDots1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_PnlDots1, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PnlDots1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PnlDots1, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PnlDots1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PnlDot1 = lv_obj_create(ui_PnlDots1);
lv_obj_set_width( ui_PnlDot1, 7);
lv_obj_set_height( ui_PnlDot1, 7);
lv_obj_set_align( ui_PnlDot1, LV_ALIGN_LEFT_MID );
lv_obj_clear_flag( ui_PnlDot1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_PnlDot2 = lv_obj_create(ui_PnlDots1);
lv_obj_set_width( ui_PnlDot2, 7);
lv_obj_set_height( ui_PnlDot2, 7);
lv_obj_set_align( ui_PnlDot2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PnlDot2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_PnlDot2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PnlDot2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PnlDot2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PnlDot2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PnlDot3 = lv_obj_create(ui_PnlDots1);
lv_obj_set_width( ui_PnlDot3, 7);
lv_obj_set_height( ui_PnlDot3, 7);
lv_obj_set_align( ui_PnlDot3, LV_ALIGN_RIGHT_MID );
lv_obj_clear_flag( ui_PnlDot3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BtnHumi1 = lv_btn_create(ui_ScreenSensor);
lv_obj_set_width( ui_BtnHumi1, 140);
lv_obj_set_height( ui_BtnHumi1, 200);
lv_obj_set_x( ui_BtnHumi1, 148 );
lv_obj_set_y( ui_BtnHumi1, 80 );
lv_obj_set_align( ui_BtnHumi1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BtnHumi1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BtnHumi1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_BtnHumi1, lv_color_hex(0x4EACE4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BtnHumi1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImgHumi1 = lv_img_create(ui_BtnHumi1);
lv_img_set_src(ui_ImgHumi1, &ui_img_humidity_2_png);
lv_obj_set_width( ui_ImgHumi1, LV_SIZE_CONTENT);  /// 44
lv_obj_set_height( ui_ImgHumi1, LV_SIZE_CONTENT);   /// 53
lv_obj_set_x( ui_ImgHumi1, -45 );
lv_obj_set_y( ui_ImgHumi1, -70 );
lv_obj_set_align( ui_ImgHumi1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImgHumi1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImgHumi1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LblTitleHumi1 = lv_label_create(ui_BtnHumi1);
lv_obj_set_width( ui_LblTitleHumi1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LblTitleHumi1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LblTitleHumi1, 15 );
lv_obj_set_y( ui_LblTitleHumi1, -70 );
lv_obj_set_align( ui_LblTitleHumi1, LV_ALIGN_CENTER );
lv_label_set_text(ui_LblTitleHumi1,"Humidity");
lv_obj_set_style_text_font(ui_LblTitleHumi1, &ui_font_font0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LblDataHumi1 = lv_label_create(ui_BtnHumi1);
lv_obj_set_width( ui_LblDataHumi1, 80);
lv_obj_set_height( ui_LblDataHumi1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LblDataHumi1, -30 );
lv_obj_set_y( ui_LblDataHumi1, 0 );
lv_obj_set_align( ui_LblDataHumi1, LV_ALIGN_CENTER );
lv_label_set_text(ui_LblDataHumi1,"--");
lv_obj_set_style_text_align(ui_LblDataHumi1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LblDataHumi1, &ui_font_font2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LblUnitHumi1 = lv_label_create(ui_BtnHumi1);
lv_obj_set_width( ui_LblUnitHumi1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LblUnitHumi1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LblUnitHumi1, 25 );
lv_obj_set_y( ui_LblUnitHumi1, 0 );
lv_obj_set_align( ui_LblUnitHumi1, LV_ALIGN_CENTER );
lv_label_set_text(ui_LblUnitHumi1,"%");
lv_obj_set_style_text_font(ui_LblUnitHumi1, &ui_font_font0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BtnCOt1 = lv_btn_create(ui_ScreenSensor);
lv_obj_set_width( ui_BtnCOt1, 436);
lv_obj_set_height( ui_BtnCOt1, 140);
lv_obj_set_x( ui_BtnCOt1, 0 );
lv_obj_set_y( ui_BtnCOt1, -100 );
lv_obj_set_align( ui_BtnCOt1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BtnCOt1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BtnCOt1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_BtnCOt1, lv_color_hex(0x529D53), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BtnCOt1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImgCOt1 = lv_img_create(ui_BtnCOt1);
lv_img_set_src(ui_ImgCOt1, &ui_img_co2_png);
lv_obj_set_width( ui_ImgCOt1, LV_SIZE_CONTENT);  /// 44
lv_obj_set_height( ui_ImgCOt1, LV_SIZE_CONTENT);   /// 53
lv_obj_set_x( ui_ImgCOt1, -184 );
lv_obj_set_y( ui_ImgCOt1, -40 );
lv_obj_set_align( ui_ImgCOt1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImgCOt1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImgCOt1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LblTitleCOt1 = lv_label_create(ui_BtnCOt1);
lv_obj_set_width( ui_LblTitleCOt1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LblTitleCOt1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LblTitleCOt1, -134 );
lv_obj_set_y( ui_LblTitleCOt1, -40 );
lv_obj_set_align( ui_LblTitleCOt1, LV_ALIGN_CENTER );
lv_label_set_text(ui_LblTitleCOt1,"CO2");
lv_obj_set_style_text_font(ui_LblTitleCOt1, &ui_font_font0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LblDataCOt1 = lv_label_create(ui_BtnCOt1);
lv_obj_set_width( ui_LblDataCOt1, 200);
lv_obj_set_height( ui_LblDataCOt1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LblDataCOt1, -90 );
lv_obj_set_y( ui_LblDataCOt1, -1 );
lv_obj_set_align( ui_LblDataCOt1, LV_ALIGN_CENTER );
lv_label_set_text(ui_LblDataCOt1,"-- ");
lv_obj_set_style_text_align(ui_LblDataCOt1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LblDataCOt1, &ui_font_font3, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LblUnitCOt1 = lv_label_create(ui_BtnCOt1);
lv_obj_set_width( ui_LblUnitCOt1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LblUnitCOt1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LblUnitCOt1, 35 );
lv_obj_set_y( ui_LblUnitCOt1, 0 );
lv_obj_set_align( ui_LblUnitCOt1, LV_ALIGN_CENTER );
lv_label_set_text(ui_LblUnitCOt1,"ppm");
lv_obj_set_style_text_font(ui_LblUnitCOt1, &ui_font_font0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BtnTVOC1 = lv_btn_create(ui_ScreenSensor);
lv_obj_set_width( ui_BtnTVOC1, 140);
lv_obj_set_height( ui_BtnTVOC1, 200);
lv_obj_set_x( ui_BtnTVOC1, -148 );
lv_obj_set_y( ui_BtnTVOC1, 80 );
lv_obj_set_align( ui_BtnTVOC1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BtnTVOC1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BtnTVOC1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_BtnTVOC1, lv_color_hex(0xE06D3D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BtnTVOC1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImgTVOC1 = lv_img_create(ui_BtnTVOC1);
lv_img_set_src(ui_ImgTVOC1, &ui_img_tvoc_png);
lv_obj_set_width( ui_ImgTVOC1, LV_SIZE_CONTENT);  /// 44
lv_obj_set_height( ui_ImgTVOC1, LV_SIZE_CONTENT);   /// 53
lv_obj_set_x( ui_ImgTVOC1, -40 );
lv_obj_set_y( ui_ImgTVOC1, -70 );
lv_obj_set_align( ui_ImgTVOC1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImgTVOC1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImgTVOC1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LblTitleTVOC1 = lv_label_create(ui_BtnTVOC1);
lv_obj_set_width( ui_LblTitleTVOC1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LblTitleTVOC1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LblTitleTVOC1, 15 );
lv_obj_set_y( ui_LblTitleTVOC1, -70 );
lv_obj_set_align( ui_LblTitleTVOC1, LV_ALIGN_CENTER );
lv_label_set_text(ui_LblTitleTVOC1,"tVOC");
lv_obj_set_style_text_font(ui_LblTitleTVOC1, &ui_font_font0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LblDataTVOC1 = lv_label_create(ui_BtnTVOC1);
lv_obj_set_width( ui_LblDataTVOC1, 100);
lv_obj_set_height( ui_LblDataTVOC1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LblDataTVOC1, -21 );
lv_obj_set_y( ui_LblDataTVOC1, 0 );
lv_obj_set_align( ui_LblDataTVOC1, LV_ALIGN_CENTER );
lv_label_set_text(ui_LblDataTVOC1,"-- ");
lv_obj_set_style_text_align(ui_LblDataTVOC1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LblDataTVOC1, &ui_font_font2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LblUnitTVOC1 = lv_label_create(ui_BtnTVOC1);
lv_obj_set_width( ui_LblUnitTVOC1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LblUnitTVOC1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LblUnitTVOC1, 44 );
lv_obj_set_y( ui_LblUnitTVOC1, 4 );
lv_obj_set_align( ui_LblUnitTVOC1, LV_ALIGN_CENTER );
lv_label_set_text(ui_LblUnitTVOC1,"");
lv_obj_set_style_text_font(ui_LblUnitTVOC1, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BtnTmp1 = lv_btn_create(ui_ScreenSensor);
lv_obj_set_width( ui_BtnTmp1, 140);
lv_obj_set_height( ui_BtnTmp1, 200);
lv_obj_set_x( ui_BtnTmp1, 0 );
lv_obj_set_y( ui_BtnTmp1, 80 );
lv_obj_set_align( ui_BtnTmp1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BtnTmp1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BtnTmp1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_BtnTmp1, lv_color_hex(0xEEBF41), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BtnTmp1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImgTmp1 = lv_img_create(ui_BtnTmp1);
lv_img_set_src(ui_ImgTmp1, &ui_img_temp_2_png);
lv_obj_set_width( ui_ImgTmp1, LV_SIZE_CONTENT);  /// 44
lv_obj_set_height( ui_ImgTmp1, LV_SIZE_CONTENT);   /// 53
lv_obj_set_x( ui_ImgTmp1, -40 );
lv_obj_set_y( ui_ImgTmp1, -70 );
lv_obj_set_align( ui_ImgTmp1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImgTmp1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImgTmp1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LblTitleTmp1 = lv_label_create(ui_BtnTmp1);
lv_obj_set_width( ui_LblTitleTmp1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LblTitleTmp1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LblTitleTmp1, 15 );
lv_obj_set_y( ui_LblTitleTmp1, -70 );
lv_obj_set_align( ui_LblTitleTmp1, LV_ALIGN_CENTER );
lv_label_set_text(ui_LblTitleTmp1,"Temp");
lv_obj_set_style_text_font(ui_LblTitleTmp1, &ui_font_font0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LblDataTmp1 = lv_label_create(ui_BtnTmp1);
lv_obj_set_width( ui_LblDataTmp1, 80);
lv_obj_set_height( ui_LblDataTmp1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LblDataTmp1, -20 );
lv_obj_set_y( ui_LblDataTmp1, 0 );
lv_obj_set_align( ui_LblDataTmp1, LV_ALIGN_CENTER );
lv_label_set_text(ui_LblDataTmp1,"-- ");
lv_obj_set_style_text_align(ui_LblDataTmp1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LblDataTmp1, &ui_font_font2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LblUnitTmp1 = lv_label_create(ui_BtnTmp1);
lv_obj_set_width( ui_LblUnitTmp1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LblUnitTmp1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LblUnitTmp1, 35 );
lv_obj_set_y( ui_LblUnitTmp1, 0 );
lv_obj_set_align( ui_LblUnitTmp1, LV_ALIGN_CENTER );
lv_label_set_text(ui_LblUnitTmp1,"C");
lv_obj_set_style_text_font(ui_LblUnitTmp1, &ui_font_font0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BtnWifi2 = lv_btn_create(ui_ScreenSensor);
lv_obj_set_width( ui_BtnWifi2, 60);
lv_obj_set_height( ui_BtnWifi2, 60);
lv_obj_set_x( ui_BtnWifi2, -10 );
lv_obj_set_y( ui_BtnWifi2, 10 );
lv_obj_set_align( ui_BtnWifi2, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_BtnWifi2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BtnWifi2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_BtnWifi2, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BtnWifi2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_BtnWifi2, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT );

ui_LblWifiStatus2 = lv_img_create(ui_BtnWifi2);
lv_img_set_src(ui_LblWifiStatus2, &ui_img_wifi_disconet_png);
lv_obj_set_width( ui_LblWifiStatus2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LblWifiStatus2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LblWifiStatus2, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_LblWifiStatus2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_LblWifiStatus2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

}
